language: python
install:
  - pip install .
script: python -m unittest discover tests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "Q0KO1FaDw+qzc2eEZ8eThVhxqPq1Ky2YfsGUpBQFkYbKE3yyvIfYKvMkRmc2QFq9pAqLBUrz0yX1YIuDl41JmhNZ8OhOVmDT36zAbP/wCQtvY7SrmnFgBAv7cYQrOK+KtHMuwSwpTIr5LZ5WSWkgF3+a1ozEhaVeMVaSX14O3IzVnByCG0tLEx14fTxxVCvYtOEzm7FgPdvHRgKEIJHJdDl4w8GKL8r1Yxen7i9dYsaaRyDWUwx6lfGJxqnVWaPQf95ltQURYGDydnDpsfUWkG2EDAEZWYBFRC0xixGmy0vCnrQILPQP5l2KIIy0k29CAo7gkI5+1FHSSGNPli8V7uSxBSety2M6E8wqfCrFzZB7Uc8C+QF5A6SmtpBvsWfg6GGy4WNqof8CN4lz0MzuzxP4hK2wW/DQBGwMpCYVI4b9pdt7m32RlK3g8QPzsCvA/1+JdqQyk0+5COly+FAZqzjov/p0FuPsvekaEycL+HJwbS/3sJXDGD2xHwM+hf/OfW1hjiGYVS3D5bBGXJlrvP+qVlUH31lHxQrHAgy3tuDN8i8zsVzAyAw23vqpXiYgfaHc59ipWsC/mVzHNmYcJ/avRO83WOw9vvtrOdhEgftkpbBrdEAGGWx3I7wNXZ99tzQCps5i2QUOfLsW4+4gJ4IW6TnoquEpfLn3n7ecnLE="
  on:
    tags: true
